/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated.training'
import { Route as AuthenticatedSurveyRouteImport } from './routes/_authenticated.survey'
import { Route as AuthenticatedProgramRouteImport } from './routes/_authenticated.program'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated.plan'
import { Route as AuthenticatedPhotosRouteImport } from './routes/_authenticated.photos'
import { Route as AuthenticatedMeasurementsRouteImport } from './routes/_authenticated.measurements'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminSurveysRouteImport } from './routes/_authenticated.admin-surveys'
import { Route as AuthenticatedAdminNutriRouteImport } from './routes/_authenticated.admin-nutri'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSurveyRoute = AuthenticatedSurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgramRoute = AuthenticatedProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhotosRoute = AuthenticatedPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeasurementsRoute =
  AuthenticatedMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSurveysRoute =
  AuthenticatedAdminSurveysRouteImport.update({
    id: '/admin-surveys',
    path: '/admin-surveys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNutriRoute = AuthenticatedAdminNutriRouteImport.update({
  id: '/admin-nutri',
  path: '/admin-nutri',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-nutri': typeof AuthenticatedAdminNutriRoute
  '/admin-surveys': typeof AuthenticatedAdminSurveysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/program': typeof AuthenticatedProgramRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/training': typeof AuthenticatedTrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-nutri': typeof AuthenticatedAdminNutriRoute
  '/admin-surveys': typeof AuthenticatedAdminSurveysRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/program': typeof AuthenticatedProgramRoute
  '/survey': typeof AuthenticatedSurveyRoute
  '/training': typeof AuthenticatedTrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-nutri': typeof AuthenticatedAdminNutriRoute
  '/_authenticated/admin-surveys': typeof AuthenticatedAdminSurveysRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/measurements': typeof AuthenticatedMeasurementsRoute
  '/_authenticated/photos': typeof AuthenticatedPhotosRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/program': typeof AuthenticatedProgramRoute
  '/_authenticated/survey': typeof AuthenticatedSurveyRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-nutri'
    | '/admin-surveys'
    | '/dashboard'
    | '/documents'
    | '/measurements'
    | '/photos'
    | '/plan'
    | '/program'
    | '/survey'
    | '/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-nutri'
    | '/admin-surveys'
    | '/dashboard'
    | '/documents'
    | '/measurements'
    | '/photos'
    | '/plan'
    | '/program'
    | '/survey'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/admin-nutri'
    | '/_authenticated/admin-surveys'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/measurements'
    | '/_authenticated/photos'
    | '/_authenticated/plan'
    | '/_authenticated/program'
    | '/_authenticated/survey'
    | '/_authenticated/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/survey': {
      id: '/_authenticated/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof AuthenticatedSurveyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/program': {
      id: '/_authenticated/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof AuthenticatedProgramRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/photos': {
      id: '/_authenticated/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AuthenticatedPhotosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/measurements': {
      id: '/_authenticated/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof AuthenticatedMeasurementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-surveys': {
      id: '/_authenticated/admin-surveys'
      path: '/admin-surveys'
      fullPath: '/admin-surveys'
      preLoaderRoute: typeof AuthenticatedAdminSurveysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-nutri': {
      id: '/_authenticated/admin-nutri'
      path: '/admin-nutri'
      fullPath: '/admin-nutri'
      preLoaderRoute: typeof AuthenticatedAdminNutriRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminNutriRoute: typeof AuthenticatedAdminNutriRoute
  AuthenticatedAdminSurveysRoute: typeof AuthenticatedAdminSurveysRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedMeasurementsRoute: typeof AuthenticatedMeasurementsRoute
  AuthenticatedPhotosRoute: typeof AuthenticatedPhotosRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedProgramRoute: typeof AuthenticatedProgramRoute
  AuthenticatedSurveyRoute: typeof AuthenticatedSurveyRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminNutriRoute: AuthenticatedAdminNutriRoute,
  AuthenticatedAdminSurveysRoute: AuthenticatedAdminSurveysRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedMeasurementsRoute: AuthenticatedMeasurementsRoute,
  AuthenticatedPhotosRoute: AuthenticatedPhotosRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedProgramRoute: AuthenticatedProgramRoute,
  AuthenticatedSurveyRoute: AuthenticatedSurveyRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
